const { createPool } = require("../configs/database");
const oracledb = require("oracledb");

const loadFavicon = async (req, res) => {
    res.status(204).end();
}

const checkExistAndCreateTable = async (req, res) => {
    let connection;
    try {
        const pool = await createPool();
        connection = await pool.getConnection();
        console.log(">> Connected success");
        // Check if table exists
        try {
            const checkTable = await connection.execute(
                `select count(*) from USER_TABLES where table_name = 'Employee'`,
            );

            const tableExists = checkTable.rows[0][0] > 0;

            if (tableExists) {
                console.log("Table exists");
            } else {
                const createTable = await connection.execute(
                    `CREATE TABLE Employee (
                        EmployeeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        FirstName VARCHAR2(50),
                        LastName VARCHAR2(50),
                        DepartmentID NUMBER,
                        Salary NUMBER
                    )`,
                    [],
                    { autoCommit: true }
                );
                console.log("Table created successfully");
            }

        } catch (err) {
            console.error("Error checking or creating table:");
        }
    } catch (err) {
        console.log(">> Failed to connect to database")
    }
}

const getRootPage = async (req, res) => {
    res.status(200).send({
        message: "Welcome to the API",
        status: "success",
    });
}

const addUserAPI = async (req, res) => {
    await checkExistAndCreateTable(req, res);
    const { EmployeeID, FirstName, LastName, DepartmentID, Salary } = req.body;
    let connection;
    try {
        const pool = await createPool();
        connection = await pool.getConnection();
        console.log(">> Connected success");
        // Insert data into the table
        const insertData = await connection.execute(
            `INSERT INTO Employee (FirstName, LastName, DepartmentID, Salary) VALUES (:1, :2, :3, :4)`,
            [FirstName, LastName, DepartmentID, Salary],
            { autoCommit: true }
        );
        console.log("Data inserted successfully");
        res.status(200).send({
            message: "User added successfully",
            status: "success",
        });
    } catch (err) {
        console.error("Error inserting data:", err);
        res.status(500).send({
            message: "Error adding user",
            status: "error",
        });
    } finally {
        if (connection) {
            connection.release();
        }
    }
}

const showUsersAPI = async (req, res) => {
    await checkExistAndCreateTable(req, res);
    let connection;
    try {
        const pool = await createPool();
        connection = await pool.getConnection();
        console.log(">> Connected success");
        // Select data from the table
        const selectData = await connection.execute(
            `SELECT * FROM Employee`,
            [],
            { outFormat: oracledb.OBJECT }
        );
        console.log("Data selected successfully");
        res.status(200).send({
            message: "Users retrieved successfully",
            status: "success",
            data: selectData.rows,
        });
    } catch (err) {
        console.error("Error selecting data:", err);
        res.status(500).send({
            message: "Error retrieving users",
            status: "error",
        });
    } finally {
        if (connection) {
            connection.release();
        }
    }
}

const editUserAPI = async (req, res) => {
    await checkExistAndCreateTable(req, res);
    const { EmployeeID, FirstName, LastName, DepartmentID, Salary } = req.body;
    let connection;
    try {
        const pool = await createPool();
        connection = await pool.getConnection();
        console.log(">> Connected success");
        // Update data in the table
        const updateData = await connection.execute(
            `UPDATE Employee SET FirstName = :1, LastName = :2, DepartmentID = :3, Salary = :4 WHERE EmployeeID = :5`,
            [FirstName, LastName, DepartmentID, Salary, EmployeeID],
            { autoCommit: true }
        );
        console.log("Data updated successfully");
        res.status(200).send({
            message: "User updated successfully",
            status: "success",
        });
    } catch (err) {
        console.error("Error updating data:", err);
        res.status(500).send({
            message: "Error updating user",
            status: "error",
        });
    } finally {
        if (connection) {
            connection.release();
        }
    }
}

const deleteUserAPI = async (req, res) => {
    await checkExistAndCreateTable(req, res);
    const { EmployeeID } = req.body;
    let connection;
    try {
        const pool = await createPool();
        connection = await pool.getConnection();
        console.log(">> Connected success");
        // Delete data from the table
        const deleteData = await connection.execute(
            `DELETE FROM Employee WHERE EmployeeID = :1`,
            [EmployeeID],
            { autoCommit: true }
        );
        console.log("Data deleted successfully");
        res.status(200).send({
            message: "User deleted successfully",
            status: "success",
        });
    } catch (err) {
        console.error("Error deleting data:", err);
        res.status(500).send({
            message: "Error deleting user",
            status: "error",
        });
    } finally {
        if (connection) {
            connection.release();
        }
    }
}

module.exports = {
    loadFavicon,
    getRootPage,
    addUserAPI,
    showUsersAPI,
}